### ISSUE TITLE
g15macro not working under Ubuntu 19.10

### ISSUE THREAD

**Issue by VincentSC** [berendt/g510s#3]
g15macro seems not to work on Ubuntu 19.04 ("undefined reference to symbol 'pthread_join@@GLIBC_2.2.5'").

**Comment by berendt** [comment]
I don't know. I never used it under Ubuntu 19.X and didn't use the keyboard anymore.
